### ISSUE TITLE
sprite.png 404 (Not Found)

### ISSUE THREAD

**Issue by joshuadiezmo** [2createStudio/postcss-sprites#92] opened 2017-05-26 10:28 UTC
![image](https://cloud.githubusercontent.com/assets/8644115/26491157/fb6f9372-4240-11e7-8bfa-58e416e0bda5.png)

sprite load as text/html, not png. help.

**Comment by vvasilev-** [comment] 2017-05-26 11:06
Hey @ReverseFlash28! 

Could you post more information about your setup? 😄

**Comment by joshuadiezmo** [comment] 2017-05-26 11:58
when I run "npm run dist" it cannot create sprite.png on assets folder

**Comment by vvasilev-** [comment] 2017-05-26 12:12
@ReverseFlash28 I understand that you have a problem but I can't help you without more details about your setup. What kind of build process do you use? What is your folder structure?

**Comment by joshuadiezmo** [comment] 2017-05-26 12:21
its working on dev, but i cannot use it on production.

this is my folder stucture
![image](https://cloud.githubusercontent.com/assets/8644115/26494294/948ac6b2-4250-11e7-8d62-44cd0f58b38e.png)

and this is my config

```
var postcss = require('postcss');
var postcssSprites = require('postcss-sprites');
let path = require('path');

module.exports = {
  plugins: [
    postcssSprites({
      spritePath: path.join(__dirname, '/src/images'),
      basePath: '',
      spritesmith: {
        padding: 3
      },
      verbose: true,
      hooks: {
        onUpdateRule: function(rule, token, image) {
          var backgroundSizeX = (image.spriteWidth / image.coords.width) * 100;
          var backgroundSizeY = (image.spriteHeight / image.coords.height) * 100;
          var backgroundPositionX = (image.coords.x / (image.spriteWidth - image.coords.width)) * 100;
          var backgroundPositionY = (image.coords.y / (image.spriteHeight - image.coords.height)) * 100;

          backgroundSizeX = isNaN(backgroundSizeX)
            ? 0
            : backgroundSizeX;
          backgroundSizeY = isNaN(backgroundSizeY)
            ? 0
            : backgroundSizeY;
          backgroundPositionX = isNaN(backgroundPositionX)
            ? 0
            : backgroundPositionX;
          backgroundPositionY = isNaN(backgroundPositionY)
            ? 0
            : backgroundPositionY;

          var backgroundImage = postcss.decl({
            prop: 'background-image',
            value: 'url(' + image.spriteUrl + ')'
          });

          var backgroundSize = postcss.decl({
            prop: 'background-size',
            value: backgroundSizeX + '% ' + backgroundSizeY + '%'
          });

          var backgroundPosition = postcss.decl({
            prop: 'background-position',
            value: backgroundPositionX + '% ' + backgroundPositionY + '%'
          });

          rule.insertAfter(token, backgroundImage);
          rule.insertAfter(backgroundImage, backgroundPosition);
          rule.insertAfter(backgroundPosition, backgroundSize);
        }
      }
    }),
    require('autoprefixer')
  ]
}

```

**Comment by vvasilev-** [comment] 2017-05-26 12:25
I think the problem is in your config. 
You should have `spritePath: path.join(__dirname, '/dist/whatever'),` instead of `spritePath: path.join(__dirname, '/src/images'),`. 😄

**Comment by joshuadiezmo** [comment] 2017-05-26 12:29
yes, i already do that, then the problem is the dev,

![image](https://cloud.githubusercontent.com/assets/8644115/26494602/f5f1e646-4251-11e7-9344-a28a201e3858.png)

it cannot load the sprite

**Comment by vvasilev-** [comment] 2017-05-26 12:38
There is an easy fix for this, just pass a different path that depends on some env variable. I don't think that the problem is in `postcss-sprites` at all. How do you serve your files in dev/production?

**Comment by joshuadiezmo** [comment] 2017-05-26 13:06
now the problem is when i use it on prduction, the path is have and /dist.

i just need /assets

**Comment by vvasilev-** [comment] 2017-05-26 13:22
Please, set your CSS output folder to the [`stylesheetPath` ](https://github.com/2createStudio/postcss-sprites#stylesheetpath) option. This way the plugin will generate the correct path to your spritesheet.

**Comment by joshuadiezmo** [comment] 2017-05-26 13:44
i set it now, but i still have an error, it perfectly set to an assets but its not working. 

i have sprite.png on my assets but it still an 404 Not Found

**Comment by joshuadiezmo** [comment] 2017-05-26 13:48
i fix my issue by using express as my server for prod and did not use webpack on my production server

**Comment by joshuadiezmo** [comment] 2017-05-26 13:49
This is my express server, i create separate index file for my production. 

```
const express = require('express');
const path = require('path');

const app = express();


// Serve static assets
app.use('/assets',express.static(path.resolve(__dirname, 'dist', 'assets')));

// Always return the main index.html, so react-router render the route in the client
app.get('*', (req, res) => {
  res.sendFile(path.resolve(__dirname, 'dist', 'index.html'));
});

app.listen('8000',()=>{
  console.log('yowyow');
})
```

**Comment by vvasilev-** [comment] 2017-05-26 13:57
Can you prepare a demo repo where I can test this?

**Comment by joshuadiezmo** [comment] 2017-05-26 15:11
Sorry, my test project was on my office work computer. I will send you my test project on monday.

**Closed as completed** 2017-06-14 09:38 UTC
Labels: question
